backend:
  name: github
  repo: alberto56/test1019
  branch: main
  base_url: https://suresh-issue-82.dcycleproject.org
  auth_endpoint: /auth/github/68bc42a0ed404407b8afb35c

media_folder: "media"   # where uploads are committed in the repo
public_folder: "/media"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
